//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://customer.endpoint.earthport.com/api/merchant/v1", ConfigurationName="MerchantAPI")]
public interface MerchantAPI
{
    
    // CODEGEN: Parameter 'submitDocumentReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="submitDocumentReturn")]
    submitDocumentResponse submitDocument(submitDocumentRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customer.endpoint.earthport.com/api/merchant/v1")]
public partial class Response
{
    
    private AckType ackField;
    
    private System.Xml.XmlElement anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public AckType ack
    {
        get
        {
            return this.ackField;
        }
        set
        {
            this.ackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
    public System.Xml.XmlElement Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customer.endpoint.earthport.com/api/merchant/v1")]
public enum AckType
{
    
    /// <remarks/>
    success,
    
    /// <remarks/>
    failure,
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="submitDocument", WrapperNamespace="http://customer.endpoint.earthport.com/api/merchant/v1", IsWrapped=true)]
public partial class submitDocumentRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://customer.endpoint.earthport.com/api/merchant/v1", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Xml.XmlElement parameters;
    
    public submitDocumentRequest()
    {
    }
    
    public submitDocumentRequest(System.Xml.XmlElement parameters)
    {
        this.parameters = parameters;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="submitDocumentResponse", WrapperNamespace="http://customer.endpoint.earthport.com/api/merchant/v1", IsWrapped=true)]
public partial class submitDocumentResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://customer.endpoint.earthport.com/api/merchant/v1", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public Response submitDocumentReturn;
    
    public submitDocumentResponse()
    {
    }
    
    public submitDocumentResponse(Response submitDocumentReturn)
    {
        this.submitDocumentReturn = submitDocumentReturn;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface MerchantAPIChannel : MerchantAPI, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MerchantAPIClient : System.ServiceModel.ClientBase<MerchantAPI>, MerchantAPI
{
    
    public MerchantAPIClient()
    {
    }
    
    public MerchantAPIClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MerchantAPIClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MerchantAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MerchantAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    submitDocumentResponse MerchantAPI.submitDocument(submitDocumentRequest request)
    {
        return base.Channel.submitDocument(request);
    }
    
    public Response submitDocument(System.Xml.XmlElement parameters)
    {
        submitDocumentRequest inValue = new submitDocumentRequest();
        inValue.parameters = parameters;
        submitDocumentResponse retVal = ((MerchantAPI)(this)).submitDocument(inValue);
        return retVal.submitDocumentReturn;
    }
}
