//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="MerchantAPISoapBinding", Namespace="http://customer.endpoint.earthport.com/api/merchant/v1")]
public partial class MerchantAPIService : Microsoft.Web.Services3.WebServicesClientProtocol {
    
    private System.Threading.SendOrPostCallback submitDocumentOperationCompleted;
    
    /// <remarks/>
    public MerchantAPIService() {
        this.Url = "https://sandbox.earthport.com/MerchantAPI";
    }
    
    /// <remarks/>
    public event submitDocumentCompletedEventHandler submitDocumentCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://customer.endpoint.earthport.com/api/merchant/v1", ResponseNamespace="http://customer.endpoint.earthport.com/api/merchant/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("submitDocumentReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public Response submitDocument([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] System.Xml.XmlElement parameters) {
        object[] results = this.Invoke("submitDocument", new object[] {
                    parameters});
        return ((Response)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsubmitDocument(System.Xml.XmlElement parameters, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("submitDocument", new object[] {
                    parameters}, callback, asyncState);
    }
    
    /// <remarks/>
    public Response EndsubmitDocument(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Response)(results[0]));
    }
    
    /// <remarks/>
    public void submitDocumentAsync(System.Xml.XmlElement parameters) {
        this.submitDocumentAsync(parameters, null);
    }
    
    /// <remarks/>
    public void submitDocumentAsync(System.Xml.XmlElement parameters, object userState) {
        if ((this.submitDocumentOperationCompleted == null)) {
            this.submitDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubmitDocumentOperationCompleted);
        }
        this.InvokeAsync("submitDocument", new object[] {
                    parameters}, this.submitDocumentOperationCompleted, userState);
    }
    
    private void OnsubmitDocumentOperationCompleted(object arg) {
        if ((this.submitDocumentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.submitDocumentCompleted(this, new submitDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customer.endpoint.earthport.com/api/merchant/v1")]
public partial class Response {
    
    private AckType ackField;
    
    private System.Xml.XmlElement anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AckType ack {
        get {
            return this.ackField;
        }
        set {
            this.ackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customer.endpoint.earthport.com/api/merchant/v1")]
public enum AckType {
    
    /// <remarks/>
    success,
    
    /// <remarks/>
    failure,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void submitDocumentCompletedEventHandler(object sender, submitDocumentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class submitDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal submitDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Response Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Response)(this.results[0]));
        }
    }
}
